### ISSUE TITLE
Kitura app deployed to Bluemix does not run.

### ISSUE THREAD

**Issue by nightshiftdev** [IBM-Bluemix/Kitura-Starter#53]
Steps to reproduce.

1. Follow all instructions at: 
http://www.kitura.io/en/starter/gettingstarted.html

2. Follow all instructions at:
http://www.kitura.io/en/starter/deploying.html

3. Change permissions on files that prevent from uploading the app (https://github.com/IBM-Bluemix/Kitura-Starter/issues/52).

4. bx app push kijowski-swift-test

5. App does not start:

```
2017-06-14T09:02:37.89-0500 [APP/0]      ERR bash: Kitura-Starter: command not found
```

**Comment by nightshiftdev** [comment]
I've found the problem, I didn't change the name of the app in the manifest.yml file.

```
applications:
- name: kijowski-swift-test
  memory: 256M
  instances: 1
  random-route: true
  disk_quota: 1024M
  command: kijowski-swift-test
  buildpack: swift_buildpack
```
